### ISSUE TITLE
file argument not passing through open_eventfile() from remarkable_mouse

### ISSUE THREAD

**Issue by wrought** [Evidlo/remarkable_keyboard#3]
"./remarkable_keyboard.py", line 96, in read_tablet
    stdout = open_eventfile(args, file='/dev/input/event1')
    TypeError: open_eventfile() got an unexpected keyword argument 'file'

Unsure if it's necessary to either update `remarkable_mouse` to handle multiple events, or re-write `open_eventfile()` in `remarkable_keyboard`. It seems like a different event input is needed here.

**Comment by Evidlo** [comment]
I just pushed the updated remarkable-mouse to pypi.  Thanks.
