### ISSUE TITLE
Use for text input to rM notes?

### ISSUE THREAD

**Issue by 34r7h** [Evidlo/remarkable_keyboard#6]
Any idea how it's possible to use these mappings as a text entry?

**Comment by Evidlo** [comment]
Can you explain more what you mean?

**Comment by 34r7h** [comment]
I'm looking for an on-screen keyboard-entry text editor feature. Seems like you've done most of the gui work, so it's a question of how to render the input into a .rm file

**Comment by Evidlo** [comment]
This project is for controlling a computer using the remarkable as a touchscreen keyboard.  You might be more interested in https://github.com/dps/remarkable-keywriter

**Comment by 34r7h** [comment]
Thanks! I'll explore that route too
